/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendRealTimeRouteImport } from './routes/trend-real-time'
import { Route as TrendEvergreenRouteImport } from './routes/trend-evergreen'
import { Route as TrendAttualiRouteImport } from './routes/trend-attuali'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PianoEditorialeIndexRouteImport } from './routes/piano-editoriale.index'
import { Route as InfluencerIndexRouteImport } from './routes/influencer.index'
import { Route as CanaliInspoIndexRouteImport } from './routes/canali-inspo.index'
import { Route as InfluencerIdRouteImport } from './routes/influencer.$id'
import { Route as CanaliInspoIdRouteImport } from './routes/canali-inspo.$id'
import { Route as ApiPublicHooksUpdateTrendScoreRouteImport } from './routes/api/public/hooks/update-trend-score'
import { Route as ApiPublicHooksTriggerSyncCanaliFeedRouteImport } from './routes/api/public/hooks/trigger-sync-canali-feed'
import { Route as ApiPublicHooksTrendsJsonRouteImport } from './routes/api/public/hooks/trends-json'
import { Route as ApiPublicHooksTiktokOembedRouteImport } from './routes/api/public/hooks/tiktok-oembed'
import { Route as ApiPublicHooksSubmitManualRouteImport } from './routes/api/public/hooks/submit-manual'
import { Route as ApiPublicHooksScrapeInstagramProfileRouteImport } from './routes/api/public/hooks/scrape-instagram-profile'
import { Route as ApiPublicHooksLinkPreviewRouteImport } from './routes/api/public/hooks/link-preview'
import { Route as ApiPublicHooksDeleteTrendSubmissionRouteImport } from './routes/api/public/hooks/delete-trend-submission'
import { Route as ApiPublicHooksDeleteCanaleRouteImport } from './routes/api/public/hooks/delete-canale'
import { Route as ApiPublicHooksAddClientChannelRouteImport } from './routes/api/public/hooks/add-client-channel'

const TrendRealTimeRoute = TrendRealTimeRouteImport.update({
  id: '/trend-real-time',
  path: '/trend-real-time',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendEvergreenRoute = TrendEvergreenRouteImport.update({
  id: '/trend-evergreen',
  path: '/trend-evergreen',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendAttualiRoute = TrendAttualiRouteImport.update({
  id: '/trend-attuali',
  path: '/trend-attuali',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PianoEditorialeIndexRoute = PianoEditorialeIndexRouteImport.update({
  id: '/piano-editoriale/',
  path: '/piano-editoriale/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencerIndexRoute = InfluencerIndexRouteImport.update({
  id: '/influencer/',
  path: '/influencer/',
  getParentRoute: () => rootRouteImport,
} as any)
const CanaliInspoIndexRoute = CanaliInspoIndexRouteImport.update({
  id: '/canali-inspo/',
  path: '/canali-inspo/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencerIdRoute = InfluencerIdRouteImport.update({
  id: '/influencer/$id',
  path: '/influencer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CanaliInspoIdRoute = CanaliInspoIdRouteImport.update({
  id: '/canali-inspo/$id',
  path: '/canali-inspo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksUpdateTrendScoreRoute =
  ApiPublicHooksUpdateTrendScoreRouteImport.update({
    id: '/api/public/hooks/update-trend-score',
    path: '/api/public/hooks/update-trend-score',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTriggerSyncCanaliFeedRoute =
  ApiPublicHooksTriggerSyncCanaliFeedRouteImport.update({
    id: '/api/public/hooks/trigger-sync-canali-feed',
    path: '/api/public/hooks/trigger-sync-canali-feed',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTrendsJsonRoute =
  ApiPublicHooksTrendsJsonRouteImport.update({
    id: '/api/public/hooks/trends-json',
    path: '/api/public/hooks/trends-json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTiktokOembedRoute =
  ApiPublicHooksTiktokOembedRouteImport.update({
    id: '/api/public/hooks/tiktok-oembed',
    path: '/api/public/hooks/tiktok-oembed',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSubmitManualRoute =
  ApiPublicHooksSubmitManualRouteImport.update({
    id: '/api/public/hooks/submit-manual',
    path: '/api/public/hooks/submit-manual',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksScrapeInstagramProfileRoute =
  ApiPublicHooksScrapeInstagramProfileRouteImport.update({
    id: '/api/public/hooks/scrape-instagram-profile',
    path: '/api/public/hooks/scrape-instagram-profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLinkPreviewRoute =
  ApiPublicHooksLinkPreviewRouteImport.update({
    id: '/api/public/hooks/link-preview',
    path: '/api/public/hooks/link-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDeleteTrendSubmissionRoute =
  ApiPublicHooksDeleteTrendSubmissionRouteImport.update({
    id: '/api/public/hooks/delete-trend-submission',
    path: '/api/public/hooks/delete-trend-submission',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDeleteCanaleRoute =
  ApiPublicHooksDeleteCanaleRouteImport.update({
    id: '/api/public/hooks/delete-canale',
    path: '/api/public/hooks/delete-canale',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAddClientChannelRoute =
  ApiPublicHooksAddClientChannelRouteImport.update({
    id: '/api/public/hooks/add-client-channel',
    path: '/api/public/hooks/add-client-channel',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trend-attuali': typeof TrendAttualiRoute
  '/trend-evergreen': typeof TrendEvergreenRoute
  '/trend-real-time': typeof TrendRealTimeRoute
  '/canali-inspo/$id': typeof CanaliInspoIdRoute
  '/influencer/$id': typeof InfluencerIdRoute
  '/canali-inspo/': typeof CanaliInspoIndexRoute
  '/influencer/': typeof InfluencerIndexRoute
  '/piano-editoriale/': typeof PianoEditorialeIndexRoute
  '/api/public/hooks/add-client-channel': typeof ApiPublicHooksAddClientChannelRoute
  '/api/public/hooks/delete-canale': typeof ApiPublicHooksDeleteCanaleRoute
  '/api/public/hooks/delete-trend-submission': typeof ApiPublicHooksDeleteTrendSubmissionRoute
  '/api/public/hooks/link-preview': typeof ApiPublicHooksLinkPreviewRoute
  '/api/public/hooks/scrape-instagram-profile': typeof ApiPublicHooksScrapeInstagramProfileRoute
  '/api/public/hooks/submit-manual': typeof ApiPublicHooksSubmitManualRoute
  '/api/public/hooks/tiktok-oembed': typeof ApiPublicHooksTiktokOembedRoute
  '/api/public/hooks/trends-json': typeof ApiPublicHooksTrendsJsonRoute
  '/api/public/hooks/trigger-sync-canali-feed': typeof ApiPublicHooksTriggerSyncCanaliFeedRoute
  '/api/public/hooks/update-trend-score': typeof ApiPublicHooksUpdateTrendScoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trend-attuali': typeof TrendAttualiRoute
  '/trend-evergreen': typeof TrendEvergreenRoute
  '/trend-real-time': typeof TrendRealTimeRoute
  '/canali-inspo/$id': typeof CanaliInspoIdRoute
  '/influencer/$id': typeof InfluencerIdRoute
  '/canali-inspo': typeof CanaliInspoIndexRoute
  '/influencer': typeof InfluencerIndexRoute
  '/piano-editoriale': typeof PianoEditorialeIndexRoute
  '/api/public/hooks/add-client-channel': typeof ApiPublicHooksAddClientChannelRoute
  '/api/public/hooks/delete-canale': typeof ApiPublicHooksDeleteCanaleRoute
  '/api/public/hooks/delete-trend-submission': typeof ApiPublicHooksDeleteTrendSubmissionRoute
  '/api/public/hooks/link-preview': typeof ApiPublicHooksLinkPreviewRoute
  '/api/public/hooks/scrape-instagram-profile': typeof ApiPublicHooksScrapeInstagramProfileRoute
  '/api/public/hooks/submit-manual': typeof ApiPublicHooksSubmitManualRoute
  '/api/public/hooks/tiktok-oembed': typeof ApiPublicHooksTiktokOembedRoute
  '/api/public/hooks/trends-json': typeof ApiPublicHooksTrendsJsonRoute
  '/api/public/hooks/trigger-sync-canali-feed': typeof ApiPublicHooksTriggerSyncCanaliFeedRoute
  '/api/public/hooks/update-trend-score': typeof ApiPublicHooksUpdateTrendScoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/trend-attuali': typeof TrendAttualiRoute
  '/trend-evergreen': typeof TrendEvergreenRoute
  '/trend-real-time': typeof TrendRealTimeRoute
  '/canali-inspo/$id': typeof CanaliInspoIdRoute
  '/influencer/$id': typeof InfluencerIdRoute
  '/canali-inspo/': typeof CanaliInspoIndexRoute
  '/influencer/': typeof InfluencerIndexRoute
  '/piano-editoriale/': typeof PianoEditorialeIndexRoute
  '/api/public/hooks/add-client-channel': typeof ApiPublicHooksAddClientChannelRoute
  '/api/public/hooks/delete-canale': typeof ApiPublicHooksDeleteCanaleRoute
  '/api/public/hooks/delete-trend-submission': typeof ApiPublicHooksDeleteTrendSubmissionRoute
  '/api/public/hooks/link-preview': typeof ApiPublicHooksLinkPreviewRoute
  '/api/public/hooks/scrape-instagram-profile': typeof ApiPublicHooksScrapeInstagramProfileRoute
  '/api/public/hooks/submit-manual': typeof ApiPublicHooksSubmitManualRoute
  '/api/public/hooks/tiktok-oembed': typeof ApiPublicHooksTiktokOembedRoute
  '/api/public/hooks/trends-json': typeof ApiPublicHooksTrendsJsonRoute
  '/api/public/hooks/trigger-sync-canali-feed': typeof ApiPublicHooksTriggerSyncCanaliFeedRoute
  '/api/public/hooks/update-trend-score': typeof ApiPublicHooksUpdateTrendScoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/trend-attuali'
    | '/trend-evergreen'
    | '/trend-real-time'
    | '/canali-inspo/$id'
    | '/influencer/$id'
    | '/canali-inspo/'
    | '/influencer/'
    | '/piano-editoriale/'
    | '/api/public/hooks/add-client-channel'
    | '/api/public/hooks/delete-canale'
    | '/api/public/hooks/delete-trend-submission'
    | '/api/public/hooks/link-preview'
    | '/api/public/hooks/scrape-instagram-profile'
    | '/api/public/hooks/submit-manual'
    | '/api/public/hooks/tiktok-oembed'
    | '/api/public/hooks/trends-json'
    | '/api/public/hooks/trigger-sync-canali-feed'
    | '/api/public/hooks/update-trend-score'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/trend-attuali'
    | '/trend-evergreen'
    | '/trend-real-time'
    | '/canali-inspo/$id'
    | '/influencer/$id'
    | '/canali-inspo'
    | '/influencer'
    | '/piano-editoriale'
    | '/api/public/hooks/add-client-channel'
    | '/api/public/hooks/delete-canale'
    | '/api/public/hooks/delete-trend-submission'
    | '/api/public/hooks/link-preview'
    | '/api/public/hooks/scrape-instagram-profile'
    | '/api/public/hooks/submit-manual'
    | '/api/public/hooks/tiktok-oembed'
    | '/api/public/hooks/trends-json'
    | '/api/public/hooks/trigger-sync-canali-feed'
    | '/api/public/hooks/update-trend-score'
  id:
    | '__root__'
    | '/'
    | '/trend-attuali'
    | '/trend-evergreen'
    | '/trend-real-time'
    | '/canali-inspo/$id'
    | '/influencer/$id'
    | '/canali-inspo/'
    | '/influencer/'
    | '/piano-editoriale/'
    | '/api/public/hooks/add-client-channel'
    | '/api/public/hooks/delete-canale'
    | '/api/public/hooks/delete-trend-submission'
    | '/api/public/hooks/link-preview'
    | '/api/public/hooks/scrape-instagram-profile'
    | '/api/public/hooks/submit-manual'
    | '/api/public/hooks/tiktok-oembed'
    | '/api/public/hooks/trends-json'
    | '/api/public/hooks/trigger-sync-canali-feed'
    | '/api/public/hooks/update-trend-score'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TrendAttualiRoute: typeof TrendAttualiRoute
  TrendEvergreenRoute: typeof TrendEvergreenRoute
  TrendRealTimeRoute: typeof TrendRealTimeRoute
  CanaliInspoIdRoute: typeof CanaliInspoIdRoute
  InfluencerIdRoute: typeof InfluencerIdRoute
  CanaliInspoIndexRoute: typeof CanaliInspoIndexRoute
  InfluencerIndexRoute: typeof InfluencerIndexRoute
  PianoEditorialeIndexRoute: typeof PianoEditorialeIndexRoute
  ApiPublicHooksAddClientChannelRoute: typeof ApiPublicHooksAddClientChannelRoute
  ApiPublicHooksDeleteCanaleRoute: typeof ApiPublicHooksDeleteCanaleRoute
  ApiPublicHooksDeleteTrendSubmissionRoute: typeof ApiPublicHooksDeleteTrendSubmissionRoute
  ApiPublicHooksLinkPreviewRoute: typeof ApiPublicHooksLinkPreviewRoute
  ApiPublicHooksScrapeInstagramProfileRoute: typeof ApiPublicHooksScrapeInstagramProfileRoute
  ApiPublicHooksSubmitManualRoute: typeof ApiPublicHooksSubmitManualRoute
  ApiPublicHooksTiktokOembedRoute: typeof ApiPublicHooksTiktokOembedRoute
  ApiPublicHooksTrendsJsonRoute: typeof ApiPublicHooksTrendsJsonRoute
  ApiPublicHooksTriggerSyncCanaliFeedRoute: typeof ApiPublicHooksTriggerSyncCanaliFeedRoute
  ApiPublicHooksUpdateTrendScoreRoute: typeof ApiPublicHooksUpdateTrendScoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trend-real-time': {
      id: '/trend-real-time'
      path: '/trend-real-time'
      fullPath: '/trend-real-time'
      preLoaderRoute: typeof TrendRealTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trend-evergreen': {
      id: '/trend-evergreen'
      path: '/trend-evergreen'
      fullPath: '/trend-evergreen'
      preLoaderRoute: typeof TrendEvergreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trend-attuali': {
      id: '/trend-attuali'
      path: '/trend-attuali'
      fullPath: '/trend-attuali'
      preLoaderRoute: typeof TrendAttualiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piano-editoriale/': {
      id: '/piano-editoriale/'
      path: '/piano-editoriale'
      fullPath: '/piano-editoriale/'
      preLoaderRoute: typeof PianoEditorialeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencer/': {
      id: '/influencer/'
      path: '/influencer'
      fullPath: '/influencer/'
      preLoaderRoute: typeof InfluencerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canali-inspo/': {
      id: '/canali-inspo/'
      path: '/canali-inspo'
      fullPath: '/canali-inspo/'
      preLoaderRoute: typeof CanaliInspoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencer/$id': {
      id: '/influencer/$id'
      path: '/influencer/$id'
      fullPath: '/influencer/$id'
      preLoaderRoute: typeof InfluencerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canali-inspo/$id': {
      id: '/canali-inspo/$id'
      path: '/canali-inspo/$id'
      fullPath: '/canali-inspo/$id'
      preLoaderRoute: typeof CanaliInspoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/update-trend-score': {
      id: '/api/public/hooks/update-trend-score'
      path: '/api/public/hooks/update-trend-score'
      fullPath: '/api/public/hooks/update-trend-score'
      preLoaderRoute: typeof ApiPublicHooksUpdateTrendScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/trigger-sync-canali-feed': {
      id: '/api/public/hooks/trigger-sync-canali-feed'
      path: '/api/public/hooks/trigger-sync-canali-feed'
      fullPath: '/api/public/hooks/trigger-sync-canali-feed'
      preLoaderRoute: typeof ApiPublicHooksTriggerSyncCanaliFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/trends-json': {
      id: '/api/public/hooks/trends-json'
      path: '/api/public/hooks/trends-json'
      fullPath: '/api/public/hooks/trends-json'
      preLoaderRoute: typeof ApiPublicHooksTrendsJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/tiktok-oembed': {
      id: '/api/public/hooks/tiktok-oembed'
      path: '/api/public/hooks/tiktok-oembed'
      fullPath: '/api/public/hooks/tiktok-oembed'
      preLoaderRoute: typeof ApiPublicHooksTiktokOembedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/submit-manual': {
      id: '/api/public/hooks/submit-manual'
      path: '/api/public/hooks/submit-manual'
      fullPath: '/api/public/hooks/submit-manual'
      preLoaderRoute: typeof ApiPublicHooksSubmitManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scrape-instagram-profile': {
      id: '/api/public/hooks/scrape-instagram-profile'
      path: '/api/public/hooks/scrape-instagram-profile'
      fullPath: '/api/public/hooks/scrape-instagram-profile'
      preLoaderRoute: typeof ApiPublicHooksScrapeInstagramProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/link-preview': {
      id: '/api/public/hooks/link-preview'
      path: '/api/public/hooks/link-preview'
      fullPath: '/api/public/hooks/link-preview'
      preLoaderRoute: typeof ApiPublicHooksLinkPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/delete-trend-submission': {
      id: '/api/public/hooks/delete-trend-submission'
      path: '/api/public/hooks/delete-trend-submission'
      fullPath: '/api/public/hooks/delete-trend-submission'
      preLoaderRoute: typeof ApiPublicHooksDeleteTrendSubmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/delete-canale': {
      id: '/api/public/hooks/delete-canale'
      path: '/api/public/hooks/delete-canale'
      fullPath: '/api/public/hooks/delete-canale'
      preLoaderRoute: typeof ApiPublicHooksDeleteCanaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/add-client-channel': {
      id: '/api/public/hooks/add-client-channel'
      path: '/api/public/hooks/add-client-channel'
      fullPath: '/api/public/hooks/add-client-channel'
      preLoaderRoute: typeof ApiPublicHooksAddClientChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TrendAttualiRoute: TrendAttualiRoute,
  TrendEvergreenRoute: TrendEvergreenRoute,
  TrendRealTimeRoute: TrendRealTimeRoute,
  CanaliInspoIdRoute: CanaliInspoIdRoute,
  InfluencerIdRoute: InfluencerIdRoute,
  CanaliInspoIndexRoute: CanaliInspoIndexRoute,
  InfluencerIndexRoute: InfluencerIndexRoute,
  PianoEditorialeIndexRoute: PianoEditorialeIndexRoute,
  ApiPublicHooksAddClientChannelRoute: ApiPublicHooksAddClientChannelRoute,
  ApiPublicHooksDeleteCanaleRoute: ApiPublicHooksDeleteCanaleRoute,
  ApiPublicHooksDeleteTrendSubmissionRoute:
    ApiPublicHooksDeleteTrendSubmissionRoute,
  ApiPublicHooksLinkPreviewRoute: ApiPublicHooksLinkPreviewRoute,
  ApiPublicHooksScrapeInstagramProfileRoute:
    ApiPublicHooksScrapeInstagramProfileRoute,
  ApiPublicHooksSubmitManualRoute: ApiPublicHooksSubmitManualRoute,
  ApiPublicHooksTiktokOembedRoute: ApiPublicHooksTiktokOembedRoute,
  ApiPublicHooksTrendsJsonRoute: ApiPublicHooksTrendsJsonRoute,
  ApiPublicHooksTriggerSyncCanaliFeedRoute:
    ApiPublicHooksTriggerSyncCanaliFeedRoute,
  ApiPublicHooksUpdateTrendScoreRoute: ApiPublicHooksUpdateTrendScoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
